### ISSUE TITLE
Surreal Config Isn't Loading Anymore.

### ISSUE THREAD

**Issue by cursome** [frostedpenguin/the-glorious-dotfiles#1]
I tried to use surreal and it's not working anymore... And also it's not giving any kind of error notification... So I didn't found any kind of error messages to show you.. I think you need to try it yourself to find the issue...

**Comment by cursome** [comment]
@frostedpenguin Sorry to mention the system tray isn't working as well in gnawsome ...

**Comment by frostedpenguin** [comment]
@cursome I can not reproduce.. Can you give a bit of more information about your awesomewm and lua version?

**Comment by cursome** [comment]
> @cursome I can not reproduce.. Can you give a bit of more information about your awesomewm and lua version?

lua 5.4.4-2 and awesome-git latest

**Comment by frostedpenguin** [comment]
Hmm I have the same can you try running with [awmtt](https://aur.archlinux.org/packages/awmtt)? You will probably see errors in the terminal

**Comment by cursome** [comment]
@frostedpenguin Here's the log ....

https://privatebin.net/?bc480c90bf7390c5#CYNXN2Focg3pR4udYitcCGpn4CbWdpXoyZMVyuCdtaSQ

**Comment by frostedpenguin** [comment]
@cursome  Hello can you re-upload the logs ?? didnt have much time to look into them
