### ISSUE TITLE
[BUG] task_list accidently closes windows that were minimized

### ISSUE THREAD

**Issue by ildar** [frostedpenguin/the-glorious-dotfiles#6]
**Technical Information (please complete the following information):**
 - Distro: ALTLinux
 - Setup: Surreal
 - Awesome Build: latest

**Describe the bug**
When a window gets un-minimized, it may be unintentionally closed. That's because the window's bar length is changed and the closing X appears under the mouse.

**To Reproduce**
1. Notice where the X (closing) of a particular open window is
2. Minimize that window
3. move the mouse tho that place (p.1)
4. Mouse Left Button Down (unminimizes the window, the X moves to the place right under the cursor)
5. Mouse Left Button UP closes the window.

**Expected behavior**
the bar's length stay the same OR patch that behavior

**Comment by frostedpenguin** [comment]
hello :wave: 
I can't seem to reproduce the bar length change.. 

Can you provide some screenshots and what layout (floating, tile e.t.c.)  are you using?

**Comment by ildar** [comment]
I've made a change that switches the workspaces and window handles. So this
problem doesn't exist for me.
I'll publish my patch later.
